name: Build binaries

on: workflow_dispatch

jobs:

  build-macos:

    runs-on: macos-latest
    
    steps:
    - name: Install dependencies
      run: |
        brew install coreutils SDL2 sdl2_ttf sdl2_image
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build RELEASE
      run: make native CONF=RELEASE -j3
    - name: Run tests
      run: make test CONF=RELEASE
    - name: Get version
      run: |
        echo "POP_VERSION=`./build/darwin-x86_64/poptracker --version`" >> $GITHUB_ENV
        echo "POP_NAME=poptracker_`./build/darwin-x86_64/poptracker --version | tr '.' '-'`" >> $GITHUB_ENV 
    - name: Build DIST # this builds the app bundle, zips it and maybe .dmg in the future
      run: make CONF=DIST
    - name: Store app bundle
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.POP_NAME }}_macos
        path: build/darwin-x86_64/poptracker.app
    - name: Store ZIP/DMG
      uses: actions/upload-artifact@v2
      with:
        name: macos-dist
        path: dist
