name: CI

on:
  push:
    branches-ignore:
      - 'screenshots'
    paths-ignore:
      - '**.md'
      - 'doc/**'
  pull_request:
    branches-ignore:
      - 'screenshots'
    paths-ignore:
      - '**.md'
      - 'doc/**'

jobs:

  test-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install coreutils build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build DEBUG
      run: make native CONF=DEBUG -j2
    - name: Run tests
      run: make test CONF=DEBUG

  test-macos:

    runs-on: macos-latest
    
    steps:
    - name: Install dependencies
      run: |
        brew install coreutils SDL2 sdl2_ttf sdl2_image
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build DEBUG
      run: make native CONF=DEBUG -j2
    - name: Run tests
      run: make test CONF=DEBUG
